# Generated by Django 2.0.1 on 2018-02-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180128_1850'),
        ('users', '0002_auto_20180203_2024'),
    ]

    operations = [
    ]
