# Generated by Django 2.0.1 on 2018-02-11 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('koinrex_tx_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmations', models.IntegerField()),
                ('user_address', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=128)),
                ('from_address', models.CharField(editable=False, max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('koinrex_tx_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmations', models.IntegerField()),
                ('user_address', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=128)),
                ('to_address', models.CharField(editable=False, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=64)),
                ('fee', models.DecimalField(decimal_places=16, max_digits=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
