# Generated by Django 2.0.1 on 2018-02-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180211_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawals',
            name='fee',
        ),
        migrations.AlterField(
            model_name='deposits',
            name='confirmations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='confirmations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='to_address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
