# Generated by Django 2.0.1 on 2018-02-07 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('S', 'Send'), ('R', 'Receive')], max_length=1)),
                ('transaction_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=64)),
                ('fee', models.DecimalField(decimal_places=16, max_digits=64)),
                ('confirmations', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('COM', 'Completed')], max_length=3)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=16, max_digits=64)),
                ('usd_balance', models.DecimalField(decimal_places=8, max_digits=64)),
                ('amount_in', models.DecimalField(decimal_places=16, max_digits=64)),
                ('amount_out', models.DecimalField(decimal_places=16, max_digits=64)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet'),
        ),
    ]
