# Generated by Django 2.0.1 on 2018-01-28 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, unique=True)),
                ('secret_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('min_divisible_unit', models.DecimalField(decimal_places=10, max_digits=10)),
                ('symbol', models.CharField(max_length=10)),
                ('asset_type', models.CharField(choices=[('FOO', 'Footype'), ('BAR', 'Bartype')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('S', 'Send'), ('R', 'Receive')], max_length=1)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=100)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=100)),
                ('confirmations', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('COM', 'Completed')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=100)),
                ('usd_balance', models.DecimalField(decimal_places=5, max_digits=100)),
                ('amount_in', models.DecimalField(decimal_places=10, max_digits=100)),
                ('amount_out', models.DecimalField(decimal_places=10, max_digits=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wallet.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='address',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Currency'),
        ),
    ]
