# Generated by Django 2.0.1 on 2018-02-07 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_key', models.CharField(default='L3pbFwdYwKbgaMswN3sku2bMtSMeJPhdR5z9BGF8xmXN4MMcPxZw', editable=False, max_length=64, unique=True)),
                ('p_key', models.CharField(default='1EZjhfBpKTh3pypLv9raQwUg85izvjubbv', editable=False, max_length=34, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('min_divisible_unit', models.DecimalField(decimal_places=16, max_digits=16)),
                ('symbol', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('S', 'Send'), ('R', 'Receive')], max_length=1)),
                ('transaction_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=64)),
                ('fee', models.DecimalField(decimal_places=16, max_digits=64)),
                ('confirmations', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('COM', 'Completed')], max_length=3)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=16, max_digits=64)),
                ('usd_balance', models.DecimalField(decimal_places=8, max_digits=64)),
                ('amount_in', models.DecimalField(decimal_places=16, max_digits=64)),
                ('amount_out', models.DecimalField(decimal_places=16, max_digits=64)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wallet.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='address',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Currency'),
        ),
    ]
