# Generated by Django 2.0.1 on 2018-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='p_key',
            field=models.CharField(default='1KLbRCFaVHPyCX1JxstntU6C7CYEcTuF91', editable=False, max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='s_key',
            field=models.CharField(default='KyRMqAN1hETMNHZSpV5GftEfugFvFq4DaMwCp5FQGPGKYuBGLSeV', editable=False, max_length=64, unique=True),
        ),
    ]
