# Generated by Django 2.0.1 on 2018-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='p_key',
            field=models.CharField(default='1KKMHz7mkHcgxLN9UVBscca2rTUL14DVmP', editable=False, max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='s_key',
            field=models.CharField(default='KxSF42pEsz5Hk2CJkaXTC23mGKUSPNoQ9fQDr2tVX2hck7d11n3o', editable=False, max_length=64, unique=True),
        ),
    ]
