# Generated by Django 2.0.1 on 2018-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180128_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='public_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='secret_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='min_divisible_unit',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=16, max_digits=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=16, max_digits=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount_in',
            field=models.DecimalField(decimal_places=16, max_digits=64),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount_out',
            field=models.DecimalField(decimal_places=16, max_digits=64),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=16, max_digits=64),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usd_balance',
            field=models.DecimalField(decimal_places=8, max_digits=64),
        ),
    ]
