# Generated by Django 2.0.1 on 2018-02-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20180128_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='asset_type',
        ),
    ]
