# Generated by Django 2.0.1 on 2018-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_currency_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='secret_key',
        ),
        migrations.AlterField(
            model_name='address',
            name='public_key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
