# Generated by Django 2.0.1 on 2018-02-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20180201_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='public_key',
        ),
    ]
