# Generated by Django 2.0.1 on 2018-02-06 11:26

from django.db import migrations, models
import wallet.wrappers


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_address_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='address',
            name='Public Key',
            field=models.CharField(default=wallet.wrappers.Keygen.pub_key, editable=False, max_length=34, unique=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Secret Key',
            field=models.CharField(default=wallet.wrappers.Keygen.generate_key, editable=False, max_length=64, unique=True),
        ),
    ]
