# Generated by Django 2.0.1 on 2018-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitecoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('currency_min_divisible_unit', models.DecimalField(decimal_places=16, max_digits=16)),
                ('currency_symbol', models.CharField(max_length=16)),
                ('sec_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('pub_key', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Litecoin Address',
                'verbose_name_plural': 'Litecoin Addresses',
            },
        ),
    ]
