# Generated by Django 2.0.1 on 2018-02-09 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sec_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('pub_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('transaction_count', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=8, max_digits=8)),
                ('amount_in', models.DecimalField(decimal_places=8, max_digits=8)),
                ('amount_out', models.DecimalField(decimal_places=8, max_digits=8)),
                ('currency_name', models.CharField(editable=False, max_length=64)),
                ('currency_ticker', models.CharField(editable=False, max_length=8)),
                ('currency_min_div_unit', models.DecimalField(decimal_places=8, editable=False, max_digits=8)),
                ('currency_symbol', models.CharField(editable=False, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitcoin Address',
                'verbose_name_plural': 'Bitcoin Addresses',
            },
        ),
        migrations.CreateModel(
            name='LitecoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sec_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('pub_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('transaction_count', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=8, max_digits=8)),
                ('amount_in', models.DecimalField(decimal_places=8, max_digits=8)),
                ('amount_out', models.DecimalField(decimal_places=8, max_digits=8)),
                ('currency_name', models.CharField(editable=False, max_length=64)),
                ('currency_ticker', models.CharField(editable=False, max_length=8)),
                ('currency_min_div_unit', models.DecimalField(decimal_places=8, editable=False, max_digits=8)),
                ('currency_symbol', models.CharField(editable=False, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litecoin Address',
                'verbose_name_plural': 'Litecoin Addresses',
            },
        ),
    ]
