# Generated by Django 2.0.1 on 2018-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=16, default=1e-08, max_digits=16),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=16, default=1e-08, max_digits=16),
        ),
    ]
