# Generated by Django 2.0.1 on 2018-02-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoinaddress',
            name='usd_balance',
        ),
        migrations.RemoveField(
            model_name='litecoinaddress',
            name='usd_balance',
        ),
    ]
