# Generated by Django 2.0.1 on 2018-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='amount_in',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='amount_out',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=12, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_name',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_ticker',
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='amount_in',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='amount_out',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=12, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_name',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_ticker',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
