# Generated by Django 2.0.1 on 2018-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0002_auto_20180208_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_name',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_symbol',
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_ticker',
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_name',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_symbol',
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_ticker',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
