# Generated by Django 2.0.1 on 2018-02-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0002_auto_20180209_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinaddress',
            old_name='amount_in',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='bitcoinaddress',
            old_name='amount_out',
            new_name='amount_sent',
        ),
        migrations.RenameField(
            model_name='litecoinaddress',
            old_name='amount_in',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='litecoinaddress',
            old_name='amount_out',
            new_name='amount_sent',
        ),
    ]
