# Generated by Django 2.0.1 on 2018-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0003_auto_20180210_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='amount_received',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='amount_sent',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='amount_received',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='amount_sent',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=32),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
