# Generated by Django 2.0.1 on 2018-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybag', '0003_auto_20180208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=16, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='litecoinaddress',
            name='currency_min_div_unit',
            field=models.DecimalField(decimal_places=16, editable=False, max_digits=16),
        ),
    ]
